# Defines the configuration version.
# The only possible value is "2".
version: "2"
linters:
  # Enable specific linter.
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - exhaustive
    - revive

  # All available settings of specific linters.
  settings:
    exhaustive:
      # Program elements to check for exhaustiveness.
      # Default: [ switch ]
      check:
        - switch
        - map
      # Presence of "default" case in switch statements satisfies exhaustiveness,
      # even if all enum members are not listed.
      # Default: false
      default-signifies-exhaustive: true

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    # Predefined exclusion rules.
    # Default: []
    presets:
      - std-error-handling

    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      - linters:
          - revive
        text: 'indent-error-flow: if block ends with a return statement, so drop this else and outdent its block'
      - linters:
          - revive
        path: ast/ast.go
        text: 'exported: exported method \w+\.(Start|End) should have comment or be unexported'

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt

  # Formatters settings.
  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`,
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard                       # Standard section: captures all standard packages.
        - default                        # Default section: contains all imports that could not be matched to another section type.
        - localmodule                    # Local module section: contains all local packages. This section is not present unless explicitly enabled.

      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true

    gofmt:
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: interface{}
          replacement: any
