// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[keywordsStart-2]
	_ = x[Print-3]
	_ = x[Var-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[Nil-7]
	_ = x[If-8]
	_ = x[Else-9]
	_ = x[And-10]
	_ = x[Or-11]
	_ = x[While-12]
	_ = x[For-13]
	_ = x[Break-14]
	_ = x[Continue-15]
	_ = x[Fun-16]
	_ = x[Return-17]
	_ = x[Class-18]
	_ = x[This-19]
	_ = x[Super-20]
	_ = x[Static-21]
	_ = x[Get-22]
	_ = x[Set-23]
	_ = x[Try-24]
	_ = x[keywordsEnd-25]
	_ = x[Ident-26]
	_ = x[String-27]
	_ = x[Number-28]
	_ = x[Comment-29]
	_ = x[symbolsStart-30]
	_ = x[Semicolon-31]
	_ = x[Comma-32]
	_ = x[Dot-33]
	_ = x[Equal-34]
	_ = x[Plus-35]
	_ = x[Minus-36]
	_ = x[Asterisk-37]
	_ = x[Slash-38]
	_ = x[Percent-39]
	_ = x[Less-40]
	_ = x[LessEqual-41]
	_ = x[Greater-42]
	_ = x[GreaterEqual-43]
	_ = x[EqualEqual-44]
	_ = x[BangEqual-45]
	_ = x[Bang-46]
	_ = x[Question-47]
	_ = x[Colon-48]
	_ = x[LeftParen-49]
	_ = x[RightParen-50]
	_ = x[LeftBrack-51]
	_ = x[RightBrack-52]
	_ = x[LeftBrace-53]
	_ = x[RightBrace-54]
	_ = x[symbolsEnd-55]
	_ = x[typesEnd-56]
}

const _Type_name = "IllegalEOFkeywordsStartprintvartruefalsenilifelseandorwhileforbreakcontinuefunreturnclassthissuperstaticgetsettrykeywordsEndIdentStringNumberCommentsymbolsStart;,.=+-*/%<<=>>===!=!?:()[]{}symbolsEndtypesEnd"

var _Type_index = [...]uint8{0, 7, 10, 23, 28, 31, 35, 40, 43, 45, 49, 52, 54, 59, 62, 67, 75, 78, 84, 89, 93, 98, 104, 107, 110, 113, 124, 129, 135, 141, 148, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 172, 173, 175, 177, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 198, 206}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
