// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[keywordsStart-2]
	_ = x[Print-3]
	_ = x[Var-4]
	_ = x[True-5]
	_ = x[False-6]
	_ = x[Nil-7]
	_ = x[If-8]
	_ = x[Else-9]
	_ = x[And-10]
	_ = x[Or-11]
	_ = x[While-12]
	_ = x[For-13]
	_ = x[Break-14]
	_ = x[Continue-15]
	_ = x[Fun-16]
	_ = x[Return-17]
	_ = x[Class-18]
	_ = x[This-19]
	_ = x[Super-20]
	_ = x[Static-21]
	_ = x[Get-22]
	_ = x[Set-23]
	_ = x[keywordsEnd-24]
	_ = x[Ident-25]
	_ = x[String-26]
	_ = x[Number-27]
	_ = x[Comment-28]
	_ = x[symbolsStart-29]
	_ = x[Semicolon-30]
	_ = x[Comma-31]
	_ = x[Dot-32]
	_ = x[Equal-33]
	_ = x[Plus-34]
	_ = x[Minus-35]
	_ = x[Asterisk-36]
	_ = x[Slash-37]
	_ = x[Percent-38]
	_ = x[Less-39]
	_ = x[LessEqual-40]
	_ = x[Greater-41]
	_ = x[GreaterEqual-42]
	_ = x[EqualEqual-43]
	_ = x[BangEqual-44]
	_ = x[Bang-45]
	_ = x[Question-46]
	_ = x[Colon-47]
	_ = x[LeftParen-48]
	_ = x[RightParen-49]
	_ = x[LeftBrace-50]
	_ = x[RightBrace-51]
	_ = x[symbolsEnd-52]
	_ = x[typesEnd-53]
}

const _Type_name = "IllegalEOFkeywordsStartprintvartruefalsenilifelseandorwhileforbreakcontinuefunreturnclassthissuperstaticgetsetkeywordsEndIdentStringNumberCommentsymbolsStart;,.=+-*/%<<=>>===!=!?:(){}symbolsEndtypesEnd"

var _Type_index = [...]uint8{0, 7, 10, 23, 28, 31, 35, 40, 43, 45, 49, 52, 54, 59, 62, 67, 75, 78, 84, 89, 93, 98, 104, 107, 110, 121, 126, 132, 138, 145, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 169, 170, 172, 174, 176, 177, 178, 179, 180, 181, 182, 183, 193, 201}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
